project_name: picocrypt
builds:
  - dir: ./Picocrypt/cli/v2/picocrypt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

universal_binaries:
  - replace: true

archives:
  - files:
    - none*
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}
      {{- if eq .Arch "all" }}
      {{- else }}_{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

release:
  target_commitish: "{{ .Commit }}"

changelog:
  disable: true
